project:
  type: website

website:
  title: "Agnès Drouard | Data Analyst"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href : projects.qmd
        text: Projets

format:
  html:
    theme: 
      - flatly
    css: styles.css
    include-in-header: fonts.html
    toc: true
    toc-title: "Sur cette page" 
    language: fr



